env:
  commonjs: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  curly:
    - error
    - all
  eqeqeq: error
  wrap-iife:
    - error
    - inside
  no-use-before-define: error
  new-cap: error
  no-caller: error
  dot-notation: error
  no-undef: error
  no-cond-assign:
    - error
    - except-parens
