language: "node_js"
node_js: "0.10"

cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm

before_script:
  - npm run build

script:
  - npm test
  - npm run test-coverage
